assert-code-coverage-level: add support for PHPUnit 7.5

diff --git a/test/assert-code-coverage-level b/test/assert-code-coverage-level
--- a/test/assert-code-coverage-level
+++ b/test/assert-code-coverage-level
@@ -1,19 +1,8 @@
 #!/bin/bash
-#
-# Copyright (C) 2012 Cyril Bouthors <cyril@bouthors.org>
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software
-# Foundation, either version 3 of the License, or (at your option) any later
-# version.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License along with
-# this program. If not, see <http://www.gnu.org/licenses/>.
-#
+# Copyright (C) Cyril Bouthors - All Rights Reserved
+# Unauthorized copying of this file, via any medium is strictly prohibited
+# Proprietary and confidential
+# Written by Cyril Bouthors <cyril@boutho.rs>, 2003-2020
 
 # Error if code coverage != 100%
 
@@ -23,47 +12,51 @@ set -e -o pipefail -u
 
 if [ -z "$report_file" ]
 then
-    echo "$0: too few argument" >&2
-    exit 1
+  echo "$0: too few argument" >&2
+  exit 1
 fi
 
 if [ ! -f "$report_file" ]
 then
-    echo "$0: unable to open file $report_file" >&2
-    exit 1
+  echo "$0: unable to open file $report_file" >&2
+  exit 1
 fi
 
 phpunit_version=$(phpunit --version | awk '/^PHPUnit/ {print $2}' \
-    | cut -d. -f1,2)
+  | cut -d. -f1,2)
 
 if [ -z "$phpunit_version" ]
 then
-    echo "$0: unable to fetch PHPUnit version" >&2
-    exit 1
+  echo "$0: unable to fetch PHPUnit version" >&2
+  exit 1
 fi
 
 case "$phpunit_version" in
-    '3.4')
+  '3.4')
     coverage_percentage=$(head -63 $report_file | tail -1 | cut -d\" -f10)
-    ;;
+  ;;
 
-    '3.6')
+  '3.6')
     coverage_percentage=$(awk -F\" '/coverBarOutline/ {print $4; exit}' \
-	$report_file)
-    ;;
+      "$report_file")
+  ;;
 
-    '4.2')
-	coverage_percentage=$(grep -A3 Total $report_file \
-				     | awk '/sr-only/ {print $2}' | cut -d\> -f2)
-    ;;
+  '4.2')
+    coverage_percentage=$(grep -A3 Total $report_file \
+      | awk '/sr-only/ {print $2}' | cut -d\> -f2)
+  ;;
 
-    '5.1'|'5.4')
+  '5.1'|'5.4')
     coverage_percentage=$(head -46 $report_file |tail -1 | cut -d\" -f6)%
-    ;;
+  ;;
 
-    *)
-	echo "$0: unknown PHPUnit version $phpunit_version" >&2
-	exit 1
+  '7.5')
+    coverage_percentage=$(head -47 $report_file |tail -1 | cut -d\" -f6)%
+  ;;
+
+  *)
+    echo "$0: unknown PHPUnit version $phpunit_version" >&2
+    exit 1
 esac
 
 echo "Coverage report: $coverage_percentage"
@@ -71,5 +64,5 @@ echo "Coverage report: $coverage_percentage"
 # Check coverage percentage level
 if [ "$coverage_percentage" != '100.00%' ]
 then
-    exit 1
+  exit 1
 fi
